 version: "2"

 services:
    fuseki:
      build: ./fuseki

      entrypoint: ./fuseki-server

      environment:
        - FUSEKI_HOME=/apache-jena-fuseki-3.13.1/

      ports:
        - 3030:3030 # external:internal

      volumes:
        - ./fuseki/apache-jena-fuseki-3.13.1/run/configuration:/apache-jena-fuseki-3.13.1/run/configuration
        - ./fuseki/apache-jena-fuseki-3.13.1/tdb-data:/apache-jena-fuseki-3.13.1/tdb-data
        - ./fuseki/apache-jena-fuseki-3.13.1/run/shiro.ini:/apache-jena-fuseki-3.13.1/tdb-data/run/shiro.ini

