 version: "2"

 services:
    fuseki:
      build: ./fuseki

      entrypoint: ./fuseki-server

      environment:
        - FUSEKI_HOME=/apache-jena-fuseki-3.13.1/
        - JENA_HOME=/apache-jena-fuseki-3.13.1/

      ports:
        - 3030:3030 # external:internal

      volumes:
        - ./fuseki/apache-jena-fuseki-3.13.1/run:/apache-jena-fuseki-3.13.1/run
        - ./fuseki/apache-jena-fuseki-3.13.1/scripts:/apache-jena-fuseki-3.13.1/scripts
        - ./fuseki/apache-jena-fuseki-3.13.1/lib/fuseki-server.jar:/apache-jena-fuseki-3.13.1/lib/fuseki-server.jar # needed for tdb2loader
